name: master_router_generator
description: Master Router Generator
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  master_router:
    git:
      url: https://github.com/troyanskiy/master_router.git
      ref: master
  master_router_annotation:
    git:
      url: https://github.com/troyanskiy/master_router_annotation.git
      ref: master
  analyzer: ">=0.40.6"
  recase: ^3.0.1

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.12.2
